#### Importation de NumPy

In [1]:
import numpy as np

#### Création de Matrices avec NumPy

Création de matrices simples

In [2]:
# Création d'une matrice 2x3
matrice_2x3 = np.array([[1, 2, 3], [4, 5, 6]])

# Affichage de la matrice
print("Matrice 2x3 :")
print(matrice_2x3)

Matrice 2x3 :
[[1 2 3]
 [4 5 6]]


Création de matrices spéciales

In [3]:
# Matrice identité 3x3
matrice_identite = np.identity(3)

# Matrice de zeros 2x2
matrice_zeros = np.zeros((2, 2))

# Matrice de ones 3x3
matrice_ones = np.ones((3, 3))

# Affichage des matrices spéciales
print("Matrice Identité 3x3 :")
print(matrice_identite)

print("\nMatrice de Zeros 2x2 :")
print(matrice_zeros)

print("\nMatrice de Ones 3x3 :")
print(matrice_ones)

Matrice Identité 3x3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrice de Zeros 2x2 :
[[0. 0.]
 [0. 0.]]

Matrice de Ones 3x3 :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Opérations Matricielles de Base

Addition et Soustraction

In [4]:
# Addition de deux matrices
matrice_A = np.array([[1, 2], [3, 4]])
matrice_B = np.array([[5, 6], [7, 8]])
resultat_addition = matrice_A + matrice_B

# Soustraction de deux matrices
resultat_soustraction = matrice_A - matrice_B

# Affichage des résultats
print("Addition de Matrices :")
print(resultat_addition)

print("\nSoustraction de Matrices :")
print(resultat_soustraction)

Addition de Matrices :
[[ 6  8]
 [10 12]]

Soustraction de Matrices :
[[-4 -4]
 [-4 -4]]


Multiplication par un scalaire

In [5]:
# Multiplication d'une matrice par un scalaire
scalaire = 2
resultat_multiplication_scalaire = scalaire * matrice_A

# Affichage du résultat
print("Multiplication par un Scalaire :")
print(resultat_multiplication_scalaire)

Multiplication par un Scalaire :
[[2 4]
 [6 8]]


Multiplication Matricielle

In [6]:
# Multiplication matricielle
resultat_multiplication_matricielle = np.dot(matrice_A, matrice_B)

# Affichage du résultat
print("Multiplication Matricielle :")
print(resultat_multiplication_matricielle)

Multiplication Matricielle :
[[19 22]
 [43 50]]


#### Application Pratique - Analyse de Structures

Supposons que nous ayons une matrice de rigidité K représentant les propriétés de rigidité d’une poutre. Nous avons également un vecteur de forces F appliquées à la poutre. Nous pouvons utiliser les calculs matriciels pour résoudre le système d’équations linéaires K.δ = F pour trouver les déformations (δ	) de la poutre.	

In [7]:
# Matrice de rigidité K
matrice_rigidite = np.array([[4, -2], [-2, 4]])

# Vecteur de forces F
vecteur_forces = np.array([10, 5])

# Résolution du système linéaire K * delta = F
deformations = np.linalg.solve(matrice_rigidite, vecteur_forces)

# Affichage des déformations
print("Déformations de la Poutre :")
print(deformations)

Déformations de la Poutre :
[4.16666667 3.33333333]


#### Autres Opérations Matricielles avec NumPy

Transposition d'une Matrice

In [8]:
# Transposition d'une matrice
matrice_A = np.array([[1, 2, 3], [4, 5, 6]])
matrice_transposee = np.transpose(matrice_A)

# Affichage du résultat
print("Matrice d'Origine :")
print(matrice_A)

print("\nMatrice Transposée :")
print(matrice_transposee)

Matrice d'Origine :
[[1 2 3]
 [4 5 6]]

Matrice Transposée :
[[1 4]
 [2 5]
 [3 6]]


Calcul du Déterminant

Le déterminant d'une matrice carrée est un nombre qui peut être utilisé pour déterminer si la matrice est inversible.

In [9]:
# Calcul du déterminant
matrice_carree = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(matrice_carree)

# Affichage du résultat
print("Matrice Carrée :")
print(matrice_carree)

print(f"\nDéterminant : {determinant}")

Matrice Carrée :
[[2 3]
 [1 4]]

Déterminant : 5.000000000000001


Calcul de l'Inverse d'une matrice carrée

In [10]:
# Calcul de l'inverse
matrice_inversible = np.array([[4, 7], [2, 6]])
matrice_inverse = np.linalg.inv(matrice_inversible)

# Affichage des résultats
print("Matrice Inversible :")
print(matrice_inversible)

print("\nMatrice Inverse :")
print(matrice_inverse)

Matrice Inversible :
[[4 7]
 [2 6]]

Matrice Inverse :
[[ 0.6 -0.7]
 [-0.2  0.4]]


Valeurs Propres et Vecteurs Propres

In [11]:
# Calcul des valeurs propres et vecteurs propres
matrice_symetrique = np.array([[5, 2], [2, 3]])
valeurs_propres, vecteurs_propres = np.linalg.eig(matrice_symetrique)

# Affichage des résultats
print("Matrice Symétrique :")
print(matrice_symetrique)

print("\nValeurs Propres :")
print(valeurs_propres)

print("\nVecteurs Propres :")
print(vecteurs_propres)

Matrice Symétrique :
[[5 2]
 [2 3]]

Valeurs Propres :
[6.23606798 1.76393202]

Vecteurs Propres :
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


#### Cas d'Usage en Génie Civil

Analyse de Structures avec la Méthode des Éléments Finis
Les calculs matriciels sont fondamentaux dans la méthode des éléments finis pour résoudre des problèmes de structures complexes. Par exemple, la matrice de rigidité d'un élément fini peut être utilisée pour assembler la matrice globale de rigidité d'une structure.

In [12]:
# Matrice de rigidité d'un élément fini
matrice_rigidite_element = np.array([[2, -1], [-1, 2]])

# Assemblage de la matrice globale de rigidité
matrice_globale_rigidite = np.zeros((4, 4))

# Assemblage de la matrice (par exemple, élément à gauche en haut)
matrice_globale_rigidite[:2, :2] += matrice_rigidite_element

# Affichage de la matrice globale de rigidité
print("Matrice Globale de Rigidité :")
print(matrice_globale_rigidite)

Matrice Globale de Rigidité :
[[ 2. -1.  0.  0.]
 [-1.  2.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


**Analyse de Réseaux de Conduites**

Les ingénieurs en génie civil peuvent utiliser des calculs matriciels pour modéliser et analyser des réseaux de conduites dans les systèmes d'approvisionnement en eau ou les réseaux de distribution de gaz.

In [13]:
# Exemple simple de réseau de conduites
matrice_coefficients = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 1]])
vecteur_débits = np.array([10, 0, 5])

# Résolution du système d'équations linéaires pour les débits
vecteur_pressions = np.linalg.solve(matrice_coefficients, vecteur_débits)

# Affichage des résultats
print("Matrice des Coefficients :")
print(matrice_coefficients)

print("\nVecteur des Débits :")
print(vecteur_débits)

print("\nVecteur des Pressions :")
print(vecteur_pressions)

Matrice des Coefficients :
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]

Vecteur des Débits :
[10  0  5]

Vecteur des Pressions :
[15. 20. 25.]
